language: csharp
solution: Springboard365.Xrm.Core.sln
install:
  - nuget restore Springboard365.Xrm.Core.sln
  - nuget install NUnit.ConsoleRunner -Version 3.11.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Springboard365.Xrm.Core.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ./Springboard365.Xrm.Core.Test/bin/Release/Springboard365.Xrm.Core.Test.dll